version: '3.7'
services:
  impc-solr-documentation:
    # build: ./
    image: mouse-informatics/impc-solr-documentation
    command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar", "--server.port=8902", "--spring.profiles.active=docker"]
    environment:
      - PORT=8902
    networks:
      - production

networks:
  production:
