package org.mousephenotype.impcsolrdocumentation.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Setter
@Getter
public class Mp {
    private String mpId;
    private String mpTerm;
    private String mpDefinition;
    private List<String> mpTermSynonym;
    private List<String> altMpId;
    private List<String> childMpId;
    private List<String> childMpTerm;
    private List<String> parentMpId;
    private List<String> parentMpTerm;
    private List<String> intermediateMpId;
    private List<String> intermediateMpTerm;
    private List<String> topLevelMpId;
    private List<String> topLevelMpTerm;
    private List<String> topLevelMpTermSynonym;
    private List<String> topLevelMpTermId;
    private List<String> hpId;
    private List<String> hpTerm;
    private List<String> hpTermSynonym;
    private String dataType;
    private List<String> inferredMaId;
    private List<String> inferredMaTerm;
    private List<String> inferredIntermediateMaId;
    private List<String> inferredIntermediateMaTerm;
    private List<String> inferredSelectedTopLevelMaId;
    private List<String> inferredSelectedTopLevelMaTerm;
    private List<String> goId;
    private List<Float> pValue;
    private List<String> mgiAccessionId;
    private List<String> markerSymbol;
    private String markerAccessionId;
    private Long phenoCalls;
    private List<String> preqcGeneId;
    private List<String> markerName;
    private List<String> markerSynonym;
    private List<String> markerType;
    private List<String> humanGeneSymbol;
    private List<String> status;
    private List<String> imitsPhenotypeStarted;
    private List<String> imitsPhenotypeComplete;
    private List<String> imitsPhenotypeStatus;
    private List<String> latestProductionCentre;
    private List<String> latestPhenotypingCentre;
    private List<String> latestPhenotypeStatus;
    private Integer legacyPhenotypeStatus;
    private List<String> alleleName;
    private Boolean embryoDataAvailable;
    private List<String> type;
    private List<String> diseaseId;
    private List<String> diseaseSource;
    private List<String> diseaseTerm;
    private List<String> diseaseAlts;
    private List<String> diseaseClasses;
    private List<Boolean> humanCurated;
    private List<Boolean> mouseCurated;
    private List<Boolean> mgiPredicted;
    private List<Boolean> impcPredicted;
    private List<Boolean> mgiPredictedKnownGene;
    private List<Boolean> impcPredictedKnownGene;
    private List<Boolean> mgiNovelPredictedInLocus;
    private List<Boolean> impcNovelPredictedInLocus;
    private List<String> annotationTermId;
    private List<String> annotationTermName;
    private List<String> name;
    private List<String> accession;
    private List<String> expName;
    private String largeThumbnailFilePath;
    private String smallThumbnailFilePath;
    private List<String> symbol;
    private List<String> sangerSymbol;
    private List<String> geneName;
    private List<String> subtype;
    private List<String> geneSynonyms;
    private List<String> expNameExp;
    private List<String> symbolGene;
    private List<String> topLevel;
    private List<String> alleleSymbol;
    private List<String> alleleId;
    private List<String> strainName;
    private List<String> strainAccessionId;
    private List<String> pipelineName;
    private List<String> pipelineStableId;
    private List<String> pipelineStableKey;
    private List<String> procedureName;
    private List<String> procedureStableId;
    private List<String> procedureStableKey;
    private List<String> parameterName;
    private List<String> parameterStableId;
    private List<String> parameterStableKey;
    private List<String> text;
    private List<String> autoSuggest;
    private List<String> mixSynQf;
    private String searchTermJson;
    private String childrenJson;
    private String scrollNode;
    private Integer geneVariantMaleCount;
    private Integer geneVariantFemaleCount;
    private Integer geneVariantCount;
}
