package org.mousephenotype.impcsolrdocumentation.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Setter
@Getter
public class Mp {
    private String mp_id;
    private String mp_term;
    private String mp_definition;
    private List<String> mp_term_synonym;
    private List<String> alt_mp_id;
    private List<String> child_mp_id;
    private List<String> child_mp_term;
    private List<String> parent_mp_id;
    private List<String> parent_mp_term;
    private List<String> intermediate_mp_id;
    private List<String> intermediate_mp_term;
    private List<String> top_level_mp_id;
    private List<String> top_level_mp_term;
    private List<String> top_level_mp_term_synonym;
    private List<String> top_level_mp_term_id;
    private List<String> hp_id;
    private List<String> hp_term;
    private List<String> hp_term_synonym;
    private String data_type;
    private List<String> inferred_ma_id;
    private List<String> inferred_ma_term;
    private List<String> inferred_intermediate_ma_id;
    private List<String> inferred_intermediate_ma_term;
    private List<String> inferred_selected_top_level_ma_id;
    private List<String> inferred_selected_top_level_ma_term;
    private List<String> go_id;
    private List<Float> p_value;
    private List<String> mgi_accession_id;
    private List<String> marker_symbol;
    private String marker_accession_id;
    private Long pheno_calls;
    private List<String> preqc_gene_id;
    private List<String> marker_name;
    private List<String> marker_synonym;
    private List<String> marker_type;
    private List<String> human_gene_symbol;
    private List<String> status;
    private List<String> imits_phenotype_started;
    private List<String> imits_phenotype_complete;
    private List<String> imits_phenotype_status;
    private List<String> latest_production_centre;
    private List<String> latest_phenotyping_centre;
    private List<String> latest_phenotype_status;
    private Integer legacy_phenotype_status;
    private List<String> allele_name;
    private Boolean embryo_data_available;
    private List<String> type;
    private List<String> disease_id;
    private List<String> disease_source;
    private List<String> disease_term;
    private List<String> disease_alts;
    private List<String> disease_classes;
    private List<Boolean> human_curated;
    private List<Boolean> mouse_curated;
    private List<Boolean> mgi_predicted;
    private List<Boolean> impc_predicted;
    private List<Boolean> mgi_predicted_known_gene;
    private List<Boolean> impc_predicted_known_gene;
    private List<Boolean> mgi_novel_predicted_in_locus;
    private List<Boolean> impc_novel_predicted_in_locus;
    private List<String> annotation_term_id;
    private List<String> annotation_term_name;
    private List<String> name;
    private List<String> accession;
    private List<String> exp_name;
    private String large_thumbnail_file_path;
    private String small_thumbnail_file_path;
    private List<String> symbol;
    private List<String> sanger_symbol;
    private List<String> gene_name;
    private List<String> subtype;
    private List<String> gene_synonyms;
    private List<String> exp_name_exp;
    private List<String> symbol_gene;
    private List<String> top_level;
    private List<String> allele_symbol;
    private List<String> allele_id;
    private List<String> strain_name;
    private List<String> strain_accession_id;
    private List<String> pipeline_name;
    private List<String> pipeline_stable_id;
    private List<String> pipeline_stable_key;
    private List<String> procedure_name;
    private List<String> procedure_stable_id;
    private List<String> procedure_stable_key;
    private List<String> parameter_name;
    private List<String> parameter_stable_id;
    private List<String> parameter_stable_key;
    private List<String> text;
    private List<String> auto_suggest;
    private List<String> mix_syn_qf;
    private String search_term_json;
    private String children_json;
    private String scroll_node;
    private Integer gene_variant_male_count;
    private Integer gene_variant_female_count;
    private Integer gene_variant_count;

}
