apiVersion: v1
kind: Service
metadata:
  labels:
    app: impc-solr-documentation-production
  name: impc-solr-documentation-production
  namespace: mi-impc-solr-documentation
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31040
  selector:
    app: impc-solr-documentation-production
  type: NodePort
