apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-service-production
  name: api-service-production
  namespace: mi-impc-solr-documentation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service-production
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-service-production
    spec:
      containers:
        - image: rwilsonebi/impc-solr-documentation:latest
          imagePullPolicy: Always
          name: api-service-production
          env:
            - name: REDEPLOY_KEY
              value: "STRING_REPLACED_DURING_REDEPLOY"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
