package org.mousephenotype.impcsolrdocumentation.generator;

import org.mousephenotype.impcsolrdocumentation.model.Allele;

import java.util.List;

public class AlleleGenerator {


    public static Allele generateExampleAlleleResponse() {
        return new Allele(
            "gene",
            "MGI:123456",
            "Abc1",
            List.of("ABC1"),
            "ABC transporter 1",
            List.of("ABC1 Synonym1", "ABC1 Synonym2"),
            "protein coding",
            List.of("ENSG00000123456"),
            "true",
            "true",
            "Complete",
            "Active",
            "Production Complete",
            "Available",
            "Produced",
            "Available",
            "Produced",
            1,
            "Phenotyping Complete",
            "Project Complete",
            List.of("Centre1"),
            List.of("Centre2"),
            "1",
            1000000,
            2000000,
            "+",
            List.of("Allele1"),
            List.of("Acc1", "Acc2"),
            List.of("Status1"),
            "Status2",
            List.of("Status3"),
            List.of("Status4"),
            List.of("Centre3"),
            List.of("Centre4"),
            List.of("GO:0000001"),
            List.of("cellular process"),
            List.of("Definition1"),
            List.of("Evidence1"),
            List.of("Domain1"),
            1,
            List.of("P12345"),
            1,
            List.of("{\"pfam\":\"PF00001\"}"),
            List.of("SCDB1"),
            List.of("http://example.com"),
            List.of("Clan1"),
            List.of("ClanAcc1"),
            List.of("ClanDesc1"),
            List.of("PfamA1"),
            List.of("PfamAcc1"),
            List.of("GO:0000002"),
            List.of("biological process"),
            List.of("Category1"),
            "GF123456",
            "MGI:234567",
            List.of("Available"),
            "Project1",
            "Allele2",
            List.of("Phenotype1", "Phenotype2"),
            "Disease Type",
            List.of("Disease1", "Disease2"),
            List.of("Source1", "Source2"),
            List.of("Term1", "Term2"),
            List.of("Alt1", "Alt2"),
            List.of("Class1", "Class2"),
            List.of(true, false),
            List.of(false, true),
            List.of(true, false),
            List.of(false, true),
            List.of(true, false),
            List.of(true),
            List.of(false),
            List.of(true),
            List.of("bf1", "bf2"),
            List.of("abc1", "nubpl"),
            List.of("synonym1", "synonym2"),
            List.of("text1", "text2"),
            List.of("suggest1", "suggest2")
        );
    }

}
