package org.mousephenotype.impcsolrdocumentation.generator;

import org.mousephenotype.impcsolrdocumentation.model.Anatomy;

import java.util.List;

public class AnatomyGenerator {


    public static Anatomy generateExampleAnatomyResponse() {
        return new Anatomy(
            "Example DataType",
            List.of("ANAT:0001", "ANAT:0002"),
            "Heart",
            List.of("Cardiac", "Cor"),
            List.of(101, 102),
            List.of("ALT:001", "ALT:002"),
            "adult",
            List.of("EFO:0001", "EFO:0002"),
            List.of("EFO:0003", "EFO:0004"),
            List.of("UBERON:0001", "UBERON:0002"),
            List.of("UBERON:0003", "UBERON:0004"),
            List.of("PARENT:001", "PARENT:002"),
            List.of("Parent Heart", "Parent Lung"),
            List.of("Parent Cardiac", "Parent Pulmonary"),
            List.of("CHILD:001", "CHILD:002"),
            List.of("Child Heart", "Child Lung"),
            List.of("Child Cardiac", "Child Pulmonary"),
            List.of("INTERMEDIATE:001", "INTERMEDIATE:002"),
            List.of("Intermediate Heart", "Intermediate Lung"),
            List.of("Intermediate Cardiac", "Intermediate Pulmonary"),
            List.of("TOP:001", "TOP:002"),
            List.of("Top Level Heart", "Top Level Lung"),
            List.of("Top Cardiac", "Top Pulmonary"),
            List.of("SELECTED:001", "SELECTED:002"),
            List.of("Selected Top Heart", "Selected Top Lung"),
            List.of("Selected Top Cardiac", "Selected Top Pulmonary"),
            List.of("MP:0001", "MP:0002"),
            List.of("Phenotype 1", "Phenotype 2"),
            List.of("Synonym 1", "Synonym 2"),
            List.of("TOPMP:0001", "TOPMP:0002"),
            List.of("Top Level Phenotype 1", "Top Level Phenotype 2"),
            List.of("Top Synonym 1", "Top Synonym 2"),
            List.of("INTERMP:0001", "INTERMP:0002"),
            List.of("Intermediate Phenotype 1", "Intermediate Phenotype 2"),
            List.of("Intermediate Synonym 1", "Intermediate Synonym 2"),
            List.of("CHILDMP:0001", "CHILDMP:0002"),
            List.of("Child Phenotype 1", "Child Phenotype 2"),
            List.of("Child Synonym 1", "Child Synonym 2"),
            List.of("TERMID:0001", "TERMID:0002"),
            List.of("Term Name 1", "Term Name 2"),
            List.of("Name 1", "Name 2"),
            List.of("ACC:0001", "ACC:0002"),
            List.of("Experiment 1", "Experiment 2"),
            "/path/to/large/thumbnail.jpg",
            "/path/to/small/thumbnail.jpg",
            List.of("MA:0001", "MA:0002"),
            List.of("Ma Term 1", "Ma Term 2"),
            List.of("HMA:0001", "HMA:0002"),
            List.of("Higher Ma Term 1", "Higher Ma Term 2"),
            List.of("HMP:0001", "HMP:0002"),
            List.of("Higher Mp Term 1", "Higher Mp Term 2"),
            List.of("IHMA:0001", "IHMA:0002"),
            List.of("Inferred Higher MA 1", "Inferred Higher MA 2"),
            List.of("Annotated/Inferred MA 1", "Annotated/Inferred MA 2"),
            List.of("A/IHMA:0001", "A/IHMA:0002"),
            List.of("Symbol 1", "Symbol 2"),
            List.of("Sanger 1", "Sanger 2"),
            List.of("Gene Name 1", "Gene Name 2"),
            List.of("Subtype 1", "Subtype 2"),
            List.of("Synonym 1", "Synonym 2"),
            List.of("MATermID:0001", "MATermID:0002"),
            List.of("MA Term Name 1", "MA Term Name 2"),
            List.of("Exp Name 1", "Exp Name 2"),
            List.of("SymbolGene 1", "SymbolGene 2"),
            List.of("TopLevel 1", "TopLevel 2"),
            List.of("Text 1", "Text 2"),
            List.of("Suggest 1", "Suggest 2"),
            List.of("Anatomy Qf 1", "Anatomy Qf 2"),
            "{\"searchTerm\":\"example\"}",
            "[{\"child\":\"example1\"}, {\"child\":\"example2\"}]",
            "ScrollNodeExample"
        );
    }

}
