package org.mousephenotype.impcsolrdocumentation.generator;

import org.mousephenotype.impcsolrdocumentation.model.EssentialGenes;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

public class EssentialGenesGenerator {


    public static EssentialGenes generateExampleEssentialGenesResponse() {
        EssentialGenes essentialGenes = new EssentialGenes();
        essentialGenes.setAgeEntrezAccId(1000000L);
        essentialGenes.setAgeHumanGeneId(2000000L);
        essentialGenes.setAgeId(3000000L);
        essentialGenes.setAgeMeanGeneEffect(1.2);
        essentialGenes.setAgeRawDataId(4000000L);
        essentialGenes.setCavAlleleAccessionId("CAV:123456");
        essentialGenes.setCavAlleleSymbol("Cav1");
        essentialGenes.setCavCategory(List.of("Category1", "Category2"));
        essentialGenes.setClinDate(new Date());
        essentialGenes.setClinHaploinsufficiency("Low");
        essentialGenes.setClinHumanGeneId(5000000L);
        essentialGenes.setClinId(6000000L);
        essentialGenes.setClinReport("ClinReport1");
        essentialGenes.setClinTriplosensitivity("High");
        essentialGenes.setFBin("Fbin1");
        essentialGenes.setFBinCode("Fcode1");
        essentialGenes.setFId(7000000L);
        essentialGenes.setFOrthologId(8000000L);
        essentialGenes.setGnpBrainExpression("High");
        essentialGenes.setGnpCdsLength(9000000L);
        essentialGenes.setGnpChromosome("X");
        essentialGenes.setGnpClassicCaf(0.01);
        essentialGenes.setGnpClassicCafAfr(0.02);
        essentialGenes.setGnpClassicCafAmr(0.03);
        essentialGenes.setGnpClassicCafAsj(0.04);
        essentialGenes.setGnpClassicCafEas(0.05);
        essentialGenes.setGnpClassicCafFin(0.06);
        essentialGenes.setGnpClassicCafNfe(0.07);
        essentialGenes.setGnpClassicCafOth(0.08);
        essentialGenes.setGnpClassicCafSas(0.09);
        essentialGenes.setGnpConstraintFlag("None");
        essentialGenes.setGnpDefined(1L);
        essentialGenes.setGnpEndPosition(1001000L);
        essentialGenes.setGnpExacExpLof(0.1);
        essentialGenes.setGnpExacObsLof(10L);
        essentialGenes.setGnpExacOeLof(0.2);
        essentialGenes.setGnpExacPli(0.3);
        essentialGenes.setGnpExpHomLof(0.4);
        essentialGenes.setGnpExpLof(0.5);
        essentialGenes.setGnpExpMis(0.6);
        essentialGenes.setGnpExpMisPphen(0.7);
        essentialGenes.setGnpExpSyn(0.8);
        essentialGenes.setGnpGeneId("GNP:123456");
        essentialGenes.setGnpGeneLength(10000L);
        essentialGenes.setGnpGeneSymbol("Gnp1");
        essentialGenes.setGnpGeneType("Coding");
        essentialGenes.setGnpHumanGeneId(1100000L);
        essentialGenes.setGnpId(1200000L);
        essentialGenes.setGnpLofZ(0.9);
        essentialGenes.setGnpMaxAf(0.01);
        essentialGenes.setGnpMisZ(1.0);
        essentialGenes.setGnpMuLof(1.1);
        essentialGenes.setGnpMuMis(1.2);
        essentialGenes.setGnpMuSyn(1.3);
        essentialGenes.setGnpNSites(100L);
        essentialGenes.setGnpNoLofs(10L);
        essentialGenes.setGnpNumCodingExons(20L);
        essentialGenes.setGnpObsHetLof(5L);
        essentialGenes.setGnpObsHomLof(2L);
        essentialGenes.setGnpObsMis(30L);
        essentialGenes.setGnpObsMisPphen(15L);
        essentialGenes.setGnpObsSyn(25L);
        essentialGenes.setGnpOeLof(1.4);
        essentialGenes.setGnpOeLofLower(1.2);
        essentialGenes.setGnpOeLofUpper(1.6);
        essentialGenes.setGnpOeLofUpperBin(100L);
        essentialGenes.setGnpOeLofUpperBin6(60L);
        essentialGenes.setGnpOeLofUpperRank(50L);
        essentialGenes.setGnpOeMis(1.5);
        essentialGenes.setGnpOeMisLower(1.3);
        essentialGenes.setGnpOeMisPphen(1.7);
        essentialGenes.setGnpOeMisUpper(1.8);
        essentialGenes.setGnpOeSyn(1.9);
        essentialGenes.setGnpOeSynLower(1.7);
        essentialGenes.setGnpOeSynUpper(2.0);
        essentialGenes.setGnpP(0.01);
        essentialGenes.setGnpPAfr(0.02);
        essentialGenes.setGnpPAmr(0.03);
        essentialGenes.setGnpPAsj(0.04);
        essentialGenes.setGnpPEas(0.05);
        essentialGenes.setGnpPFin(0.06);
        essentialGenes.setGnpPNfe(0.07);
        essentialGenes.setGnpPOth(0.08);
        essentialGenes.setGnpPSas(0.09);
        essentialGenes.setGnpPli(2.1);
        essentialGenes.setGnpPnull(2.2);
        essentialGenes.setGnpPossibleLof(40L);
        essentialGenes.setGnpPossibleMis(50L);
        essentialGenes.setGnpPossibleMisPphen(25L);
        essentialGenes.setGnpPossibleSyn(35L);
        essentialGenes.setGnpPrec(2.3);
        essentialGenes.setGnpStartPosition(999000L);
        essentialGenes.setGnpSynZ(2.4);
        essentialGenes.setGnpTranscript("Transcript1");
        essentialGenes.setGnpTranscriptLevel(1L);
        essentialGenes.setGnpTranscriptType("mRNA");
        essentialGenes.setHgEnsemblGeneAccId("ENSG00000123456");
        essentialGenes.setHgEntrezGeneAccId(1000001L);
        essentialGenes.setHgHgncAccId("HGNC:123");
        essentialGenes.setHgId(1000002L);
        essentialGenes.setHgName("Human Gene 1");
        essentialGenes.setHgSymbol("HG1");
        essentialGenes.setHgncAgrAccId("AGR:123456789");
        essentialGenes.setHgncAliasName("HG1 Alias");
        essentialGenes.setHgncAliasSymbol("HGA1");
        essentialGenes.setHgncBioparadigmsSlc("SLC:12345");
        essentialGenes.setHgncCcdsAccId("CCDS12345");
        essentialGenes.setHgncCd("CD12345");
        essentialGenes.setHgncCosmic("COSM123456");
        essentialGenes.setHgncDateApprovedReserved(new GregorianCalendar(2020, Calendar.JANUARY, 1).getTime());
        essentialGenes.setHgncDateModified(new GregorianCalendar(2021, Calendar.JANUARY, 1).getTime());
        essentialGenes.setHgncDateNameChanged(new GregorianCalendar(2022, Calendar.JANUARY, 1).getTime());
        essentialGenes.setHgncDateSymbolChanged(new GregorianCalendar(2023, Calendar.JANUARY, 1).getTime());
        essentialGenes.setHgncEna("ENA12345");
        essentialGenes.setHgncEnsemblGeneAccId("ENSG00000123457");
        essentialGenes.setHgncEntrezAccId(1000003L);
        essentialGenes.setHgncEnzymeAccId("EC:3.1.3.1");
        essentialGenes.setHgncGencc("GenCC12345");
        essentialGenes.setHgncGeneGroup("Gene Group 1");
        essentialGenes.setHgncGeneGroupAccId("GGAI:12345");
        essentialGenes.setHgncGtrnadb("gtrnaDB12345");
        essentialGenes.setHgncHgncAccId("HGNC:123");
        essentialGenes.setHgncHomeodb(1000004L);
        essentialGenes.setHgncHordeAccId("HordeID12345");
        essentialGenes.setHgncHumanGeneId(1000005L);
        essentialGenes.setHgncId(1000006L);
        essentialGenes.setHgncImgt("IMGT12345");
        essentialGenes.setHgncIntermediateFilamentDb("IFDB12345");
        essentialGenes.setHgncIuphar("IUPHAR12345");
        essentialGenes.setHgncKznfGeneCatalog(1000007L);
        essentialGenes.setHgncLncipedia("Lncipedia12345");
        essentialGenes.setHgncLncrnadb("lncRNAdb12345");
        essentialGenes.setHgncLocation("1q23.3");
        essentialGenes.setHgncLocationSortable("01q23.3");
        essentialGenes.setHgncLocusGroup("protein-coding gene");
        essentialGenes.setHgncLocusType("gene with protein product");
        essentialGenes.setHgncLsdb("LSDB12345");
        essentialGenes.setHgncMamitTrnadb(1000008L);
        essentialGenes.setHgncManeSelect("MANE.Select.v7.2");
        essentialGenes.setHgncMerops("MEROPS12345");
        essentialGenes.setHgncMgiGeneAccId("MGI:1234567");
        essentialGenes.setHgncMirbase("miRBase:MI0001234");
        essentialGenes.setHgncName("Gene Name 1");
        essentialGenes.setHgncOmimAccId("OMIM:123456");
        essentialGenes.setHgncOrphanet(1000009L);
        essentialGenes.setHgncPrevName("Previous Name 1");
        essentialGenes.setHgncPrevSymbol("PrevSym1");
        essentialGenes.setHgncPseudogeneOrg("Pseudogene.org12345");
        essentialGenes.setHgncPubmedAccId("PubMed:12345678");
        essentialGenes.setHgncRefseqAccession("RefSeq:NM_000123");
        essentialGenes.setHgncRgdAccId("RGD:123456");
        essentialGenes.setHgncRnaCentralAccIds("RNAcentral:URS000075B7B7_9606");
        essentialGenes.setHgncSnornabase("snoRNABase:SNORD1234");
        essentialGenes.setHgncStatus("Approved");
        essentialGenes.setHgncSymbol("HGNC1");
        essentialGenes.setHgncUcscAccId("UCSC:uc001abc.123");
        essentialGenes.setHgncUniprotAccIds("UniProt:P12345");
        essentialGenes.setHgncVegaAccId("VEGA:OTTHUMG00000123456");
        essentialGenes.setHgsSynonyms(List.of("Synonym1", "Synonym2"));
        essentialGenes.setId("ID1");
        essentialGenes.setIdgFamily("IDG Family 1");
        essentialGenes.setIdgHumanGeneId(1000010L);
        essentialGenes.setIdgId(1000011L);
        essentialGenes.setMgEnsemblChromosome("1");
        essentialGenes.setMgEnsemblGeneAccId("ENSMUSG00000012345");
        essentialGenes.setMgEnsemblStart(100000L);
        essentialGenes.setMgEnsemblStop(200000L);
        essentialGenes.setMgEnsemblStrand("+");
        essentialGenes.setMgEntrezGeneAccId(1000012L);
        essentialGenes.setMgGenomeBuild("GRCm38");
        essentialGenes.setMgId(1000013L);
        essentialGenes.setMgMgiChromosome("1");
        essentialGenes.setMgMgiCm("23.5");
        essentialGenes.setMgMgiGeneAccId("MGI:12345678");
        essentialGenes.setMgMgiStart(150000L);
        essentialGenes.setMgMgiStop(250000L);
        essentialGenes.setMgMgiStrand("-");
        essentialGenes.setMgName("Mouse Gene 1");
        essentialGenes.setMgNcbiChromosome("1");
        essentialGenes.setMgNcbiStart(110000L);
        essentialGenes.setMgNcbiStop(210000L);
        essentialGenes.setMgNcbiStrand("+");
        essentialGenes.setMgSubtype("Subtype1");
        essentialGenes.setMgSymbol("Mg1");
        essentialGenes.setMgType("Protein-coding");
        essentialGenes.setMgsSynonyms(List.of("MgsSyn1", "MgsSyn2"));
        essentialGenes.setOCategory("Orthology Category 1");
        essentialGenes.setOHumanGeneId(2000010L);
        essentialGenes.setOId(3000010L);
        essentialGenes.setOIsMaxHumanToMouse("Yes");
        essentialGenes.setOIsMaxMouseToHuman("Yes");
        essentialGenes.setOMouseGeneId(4000010L);
        essentialGenes.setOSupport("High");
        essentialGenes.setOSupportCount(5L);
        essentialGenes.setOSupportRaw("RawSupportData1");
        essentialGenes.setPharosChr("1");
        essentialGenes.setPharosFamily("Pharos Family 1");
        essentialGenes.setPharosHumanGeneId(5000010L);
        essentialGenes.setPharosId(6000010L);
        essentialGenes.setPharosName("Pharos Gene 1");
        essentialGenes.setPharosSymbol("Pharos1");
        essentialGenes.setPharosTdl("TDL1");
        essentialGenes.setPharosUniprotAccId("UniProt:P00001");
        return essentialGenes;
    }

}
