package org.mousephenotype.impcsolrdocumentation.generator;

import org.mousephenotype.impcsolrdocumentation.model.Experiment;

import java.time.LocalDate;
import java.util.List;

public class ExperimentGenerator {


    public static Experiment generateExampleExperimentResponse() {
        List<String> exampleList = List.of("Item 1", "Item 2");

        return new Experiment(
            "1",
            "OBS0001",
            "SPEC0001",
            101L,
            "Pheno Center 1",
            201L,
            "Prod Center 2",
            301L,
            "Specimen Project 1",
            "ACC12345",
            "GeneX",
            "ALLELE123",
            "AlleleX",
            "Heterozygous",
            "Female",
            401L,
            501L,
            "Group A",
            "STRAIN001",
            "Strain X",
            "Background 1",
            "Comp1/Comp2",
            "Colony001",
            "Litter001",
            LocalDate.of(2022, 1, 1),
            "External001",
            "Adult",
            "LS123",
            601L,
            "DataSource 1",
            701L,
            "Project Y",
            801L,
            "Pipeline Z",
            "PipelineStable001",
            901L,
            "Procedure 1",
            "ProcedureStable001",
            "Group 1",
            1001L,
            "Parameter 1",
            "ParamStable001",
            "Seq001",
            "Experiment001",
            "Type 1",
            "DataType 1",
            "Source001",
            LocalDate.of(2022, 6, 1),
            "WeightParam001",
            LocalDate.of(2022, 6, 15),
            45,
            15.5f,
            5.2f,
            1,
            "Dimension 1",
            "Time 1",
            2.2f,
            "Category 1",
            "Raw Category 1",
            exampleList,
            "MetadataGroup1",
            exampleList,
            exampleList,
            exampleList,
            exampleList,
            exampleList,
            exampleList,
            exampleList,
            exampleList,
            exampleList,
            List.of("Term Synonym A", "Term Synonym B"),
            List.of("Intermediate ID A", "Intermediate ID B"),
            List.of("Intermediate Term A", "Intermediate Term B"),
            List.of("Intermediate Synonym A", "Intermediate Synonym B"),
            List.of("Parent ID A", "Parent ID B"),
            List.of("Parent Term A", "Parent Term B"),
            List.of("Parent Synonym A", "Parent Synonym B"),
            List.of("Child ID A", "Child ID B"),
            List.of("Child Term A", "Child Term B"),
            List.of("Child Synonym A", "Child Synonym B"),
            "http://example.com/download/path",
            "http://example.com/image/path",
            "JPEG",
            "1",
            List.of("Param Assoc Stable ID A", "Param Assoc Stable ID B"),
            List.of("Param Assoc Seq ID A", "Param Assoc Seq ID B"),
            List.of("Param Assoc Dim ID A", "Param Assoc Dim ID B"),
            List.of("Param Assoc Name A", "Param Assoc Name B"),
            List.of("Param Assoc Value A", "Param Assoc Value B"),
            "Dev Stage ACC",
            "Dev Stage Name",
            "Some text value",
            List.of("Sub Term ID A", "Sub Term ID B"),
            List.of("Sub Term Name A", "Sub Term Name B"),
            List.of("Sub Term Desc A", "Sub Term Desc B"),
            120,
            17
        );
    }

}
