package org.mousephenotype.impcsolrdocumentation.generator;

import org.mousephenotype.impcsolrdocumentation.model.Images;

import java.util.List;

public class ImagesGenerator {


    public static Images generateExampleImagesResponse() {
        return new Images(
            "EXP001",
            "Experiment Type",
            123,
            "Male",
            "Colony A",
            "Homozygous",
            List.of("Tag1", "Tag2"),
            List.of("Value1", "Value2"),
            List.of(1.0f),
            List.of(2.0f),
            List.of(1.0f),
            List.of(2.0f),
            List.of("Term1", "Term2"),
            List.of("Name1", "Name2"),
            "Experiment Name",
            "ACC001",
            "AlleleAcc001",
            List.of("Exp1", "Exp2"),
            List.of("Procedure1", "Procedure2"),
            List.of("Description1", "Description2"),
            List.of("Group1", "Group2"),
            "/path/to/full/resolution/file",
            "/path/to/large/thumbnail",
            "original_filename.jpg",
            "/path/to/small/thumbnail",
            "5",
            List.of("Symbol1", "Symbol2"),
            "Institute A",
            List.of("Sanger1", "Sanger2"),
            List.of("Gene1", "Gene2"),
            List.of("Subtype1", "Subtype2"),
            List.of("Synonym1", "Synonym2"),
            List.of("Allele1", "Allele2"),
            List.of("MATerm1", "MATerm2"),
            List.of("MPTermId1", "MPTermId2"),
            List.of("MPTermName1", "MPTermName2"),
            List.of("ExpNameExp1", "ExpNameExp2"),
            List.of("SymbolGene1", "SymbolGene2"),
            List.of("TopLevel1", "TopLevel2"),
            List.of("LiveSampleId1", "LiveSampleId2"),
            "DCF001",
            "DCFExp001",
            "SangerProcedure A",
            456,
            "Genotype A",
            true,
            789L,
            "Phenotyping Center A",
            "GeneAcc001",
            "GeneSymbol A",
            "Heterozygous",
            "Female",
            101112L,
            131415L,
            "Sample Group A",
            161718,
            "2021-01-01",
            "ExternalSample001",
            192021L,
            "Pipeline A",
            "PipelineStable001",
            222324L,
            "ProcedureStable001",
            252627L,
            "Parameter A",
            "ParameterStable001",
            282930L,
            "ExperimentSource001",
            "2021-02-01",
            List.of(0.01f, 0.05f),
            List.of("MGI:123456", "MGI:789012"),
            List.of("Symbol1", "Symbol2"),
            List.of("Marker Name 1", "Marker Name 2"),
            List.of("Synonym1", "Synonym2"),
            List.of("Type1", "Type2"),
            List.of("Human Symbol 1", "Human Symbol 2"),
            List.of("Status1", "Status2"),
            List.of("Centre1", "Centre2"),
            List.of("Phenotyping Centre1", "Phenotyping Centre2"),
            List.of("Status1", "Status2"),
            1,
            List.of("Disease1", "Disease2"),
            List.of("Source1", "Source2"),
            List.of("Term1", "Term2"),
            List.of("Alt1", "Alt2"),
            List.of("Class1", "Class2"),
            List.of(true, false),
            List.of(true, false),
            List.of(true, false),
            List.of(true, false),
            List.of(true, false),
            List.of(true, false),
            List.of(true, false),
            List.of(true, false),
            List.of("MP:0000001", "MP:0000002"),
            List.of("Term1", "Term2"),
            List.of("Synonym1", "Synonym2"),
            List.of("MP:0000003", "MP:0000004"),
            List.of("Top Level Term1", "Top Level Term2"),
            List.of("Top Level Synonym1", "Top Level Synonym2"),
            List.of("MP:0000005", "MP:0000006"),
            List.of("Intermediate Term1", "Intermediate Term2"),
            List.of("Intermediate Synonym1", "Intermediate Synonym2"),
            List.of("MP:0000007", "MP:0000008"),
            List.of("Child Term1", "Child Term2"),
            List.of("Child Synonym1", "Child Synonym2"),
            List.of("MP:0000009", "MP:0000010"),
            List.of("Annotated Term1", "Annotated Term2"),
            List.of("MA:0000001", "MA:0000002"),
            List.of("MATerm1", "MATerm2"),
            List.of("MASynonym1", "MASynonym2"),
            List.of("MA:0000003", "MA:0000004"),
            List.of("Selected MA Term1", "Selected MA Term2"),
            List.of("Selected MA Synonym1", "Selected MA Synonym2"),
            List.of("MA:0000005", "MA:0000006"),
            List.of("Child MATerm1", "Child MATerm2"),
            List.of("Child MASynonym1", "Child MASynonym2"),
            List.of("HP:0000001", "HP:0000002"),
            List.of("HPTerm1", "HPTerm2"),
            List.of("Text1", "Text2"),
            List.of("Suggest1", "Suggest2"),
            List.of("Search1", "Search2"),
            List.of("GeneQF1", "GeneQF2"),
            List.of("MPQF1", "MPQF2"),
            List.of("DiseaseQF1", "DiseaseQF2"),
            List.of("MAQF1", "MAQF2")
        );
    }

}
