package org.mousephenotype.impcsolrdocumentation.generator;

import org.mousephenotype.impcsolrdocumentation.model.ImpcImages;

import java.time.LocalDate;
import java.util.List;

public class ImpcImagesGenerator {


    public static ImpcImages generateExampleImpcImagesResponse() {
        return new ImpcImages(
            "1",
            "obs-001",
            "spec-001",
            100L,
            "Center A",
            101L,
            "Center B",
            200L,
            "Project X",
            "Gene-001",
            "Gn1",
            "Allele-001",
            "Al1",
            "Homozygous",
            "Male",
            300L,
            301L,
            "Group 1",
            "Strain-001",
            "Strain A",
            "Background 1",
            "Comp 1",
            "Colony-001",
            "Litter-001",
            LocalDate.of(2020, 1, 1),
            "ExtSample-001",
            "Adult",
            "LS-001",
            400L,
            "DataSource A",
            500L,
            "Project Y",
            600L,
            "Pipeline Z",
            "PSI-001",
            700L,
            "Procedure 1",
            "PS-001",
            "Group 2",
            800L,
            "Parameter 1",
            "Param-001",
            "Seq-001",
            "Exp-001",
            "Type 1",
            "Data Type 1",
            "Source-001",
            LocalDate.now(),
            "WPID-001",
            LocalDate.of(2020, 6, 15),
            100,
            20.5F,
            5.5F,
            1,
            "Dimension 1",
            "Day 1",
            1.5F,
            "Category 1",
            "Raw Category 1",
            List.of("Meta1", "Meta2"),
            "Metadata Group 1",
            List.of("MPID-1", "MPID-2"),
            List.of("Term 1", "Term 2"),
            List.of("TL-MPID-1", "TL-MPID-2"),
            List.of("Top Level Term 1", "Top Level Term 2"),
            List.of("IMPID-1", "IMPID-2"),
            List.of("Intermediate Term 1", "Intermediate Term 2"),
            List.of("AnatomyID-1", "AnatomyID-2"),
            List.of("Anatomy Term 1", "Anatomy Term 2"),
            List.of("AnatomyIDTerm-1", "AnatomyIDTerm-2"),
            List.of("Synonym 1", "Synonym 2"),
            List.of("TLAnatomyID-1", "TLAnatomyID-2"),
            List.of("TL Anatomy Term 1", "TL Anatomy Term 2"),
            List.of("TL Anatomy Term 1", "TL Anatomy Term 2"),
            List.of("STLAnatomyID-1", "STLAnatomyID-2"),
            List.of("Selected TL Anatomy Term 1", "Selected TL Anatomy Term 2"),
            List.of("Selected TL Anatomy Term 1", "Selected TL Anatomy Term 2"),
            List.of("IAnatomyID-1", "IAnatomyID-2"),
            List.of("Intermediate Anatomy Term 1", "Intermediate Anatomy Term 2"),
            List.of("Intermediate Anatomy Term 1", "Intermediate Anatomy Term 2"),
            List.of("ParentAnatomyID-1", "ParentAnatomyID-2"),
            List.of("Parent Anatomy Term 1", "Parent Anatomy Term 2"),
            List.of("Parent Anatomy Term 1", "Parent Anatomy Term 2"),
            List.of("ChildAnatomyID-1", "ChildAnatomyID-2"),
            List.of("Child Anatomy Term 1", "Child Anatomy Term 2"),
            List.of("Child Anatomy Term 1", "Child Anatomy Term 2"),
            "/path/to/download",
            "http://example.com/image",
            "jpeg",
            List.of("PAStableID-1", "PAStableID-2"),
            List.of("PASeqID-1", "PASeqID-2"),
            List.of("PADimID-1", "PADimID-2"),
            List.of("PA Name 1", "PA Name 2"),
            List.of("PA Value 1", "PA Value 2"),
            "DevStageAcc-1",
            "Development Stage 1",
            "Some text value",
            List.of("SubTermID-1", "SubTermID-2"),
            List.of("SubTerm Name 1", "SubTerm Name 2"),
            List.of("SubTerm Description 1", "SubTerm Description 2"),
            123,
            45,
            6,
            "http://example.com/download",
            "http://example.com/jpeg",
            "http://example.com/thumbnail",
            "OmeroID-1"
        );
    }

}
