package org.mousephenotype.impcsolrdocumentation.generator;

import org.mousephenotype.impcsolrdocumentation.model.Mp;

import java.util.List;

public class MpGenerator {


    public static Mp generateExampleMpResponse() {
        return new Mp(
            "MP:0000001",
            "example MP term",
            "An example definition of the MP term.",
            List.of("synonym1", "synonym2"),
            List.of("MP:0000002", "MP:0000003"),
            List.of("MP:0000004"),
            List.of("child term"),
            List.of("MP:0000005"),
            List.of("parent term"),
            List.of("MP:0000006"),
            List.of("intermediate term"),
            List.of("MP:0000007"),
            List.of("top level term"),
            List.of("top level synonym"),
            List.of("MP:0000008"),
            List.of("HP:0000001"),
            List.of("example HP term"),
            List.of("HP synonym1", "HP synonym2"),
            "example data type",
            List.of("MA:0000001"),
            List.of("inferred MA term"),
            List.of("MA:0000002"),
            List.of("intermediate MA term"),
            List.of("MA:0000003"),
            List.of("selected top level MA term"),
            List.of("GO:0000001"),
            List.of(0.01f, 0.05f),
            List.of("MGI:0000001"),
            List.of("Gene1", "Gene2"),
            "MGI:0000002",
            42L,
            List.of("Gene3", "Gene4"),
            List.of("Gene name 1", "Gene name 2"),
            List.of("Gene synonym 1", "Gene synonym 2"),
            List.of("type 1", "type 2"),
            List.of("HumanGene1", "HumanGene2"),
            List.of("status1", "status2"),
            List.of("started1", "started2"),
            List.of("complete1", "complete2"),
            List.of("status1", "status2"),
            List.of("centre1", "centre2"),
            List.of("centre3", "centre4"),
            List.of("status3", "status4"),
            1,
                List.of("Allele1"),
            true,
            List.of("type3", "type4"),
            List.of("Disease1", "Disease2"),
            List.of("source1", "source2"),
            List.of("disease term 1", "disease term 2"),
            List.of("alt1", "alt2"),
            List.of("class1", "class2"),
            List.of(false, true),
            List.of(true, false),
            List.of(false),
            List.of(true),
            List.of(true),
            List.of(false),
            List.of(true),
            List.of(false),
            List.of("Term1", "Term2"),
            List.of("Annotation term name 1", "Annotation term name 2"),
            List.of("name1", "name2"),
            List.of("Accession1", "Accession2"),
            List.of("Exp name 1", "Exp name 2"),
            "/path/to/large/thumbnail",
            "/path/to/small/thumbnail",
            List.of("Symbol1", "Symbol2"),
            List.of("Sanger1", "Sanger2"),
            List.of("Gene name 3", "Gene name 4"),
            List.of("subtype1", "subtype2"),
            List.of("Gene synonym 3", "Gene synonym 4"),
            List.of("Exp name 3", "Exp name 4"),
            List.of("SymbolGene1", "SymbolGene2"),
            List.of("TopLevel1", "TopLevel2"),
            List.of("Allele symbol 1", "Allele symbol 2"),
            List.of("Allele ID 1", "Allele ID 2"),
            List.of("Strain name 1", "Strain name 2"),
            List.of("Strain accession ID 1", "Strain accession ID 2"),
            List.of("Pipeline name 1", "Pipeline name 2"),
            List.of("Pipeline stable ID 1", "Pipeline stable ID 2"),
            List.of("Pipeline stable key 1", "Pipeline stable key 2"),
            List.of("Procedure name 1", "Procedure name 2"),
            List.of("Procedure stable ID 1", "Procedure stable ID 2"),
            List.of("Procedure stable key 1", "Procedure stable key 2"),
            List.of("Parameter name 1", "Parameter name 2"),
            List.of("Parameter stable ID 1", "Parameter stable ID 2"),
            List.of("Parameter stable key 1", "Parameter stable key 2"),
            List.of("Example text 1", "Example text 2"),
            List.of("Suggest 1", "Suggest 2"),
            List.of("Mix synonym 1", "Mix synonym 2"),
            "{\"searchTerm\":\"Example search term\"}",
            "[{\"childId\":\"C1\", \"childName\":\"Child 1\"}, {\"childId\":\"C2\", \"childName\":\"Child 2\"}]",
            "ScrollNodeExample",
            100,
            150,
            250
        );
    }

}
