package org.mousephenotype.impcsolrdocumentation.generator;

import org.mousephenotype.impcsolrdocumentation.model.Pipeline;

import java.util.List;

public class PipelineGenerator {


    public static Pipeline generateExamplePipelineResponse() {
        return new Pipeline(
            "Pipeline",
            "String",
            1L,
            101L,
            "PARAM_001",
            "Parameter Name Example",
            102L,
            201L,
            "PROC_001",
            "Procedure Name Example",
            202L,
            301L,
            "PIPE_001",
            "Pipeline Name Example",
            302L,
            true,
            "Observation Type Example",
            List.of("MP:0000001", "MP:0000002"),
            "Description Example",
            "cm",
            "kg",
            true,
            true,
            List.of("Category 1", "Category 2"),
            false,
            false,
            true,
            false,
            "Group Example",
            "Level Example",
            "Stage Example",
            "Stage Label Example",
            401L,
            List.of("MP:0000003", "MP:0000004"),
            List.of("term1", "term2"),
            List.of("synonym1", "synonym2"),
            List.of("MP:0000005"),
            List.of("top level term"),
            List.of("top level synonym"),
            List.of("MP:0000006"),
            List.of("intermediate term"),
            List.of("intermediate synonym"),
            List.of("MP:0000007"),
            List.of("MP:0000008"),
            List.of("MP:0000009"),
            List.of("abnormal term"),
            List.of("increased term"),
            List.of("decreased term"),
            List.of("HP:0000001", "HP:0000002"),
            List.of("HP term 1", "HP term 2"),
            "MA:0000001",
            "MA:0000002",
            "top level MA term",
            "MA:0000003",
            "MA term",
            List.of("MA synonym 1", "MA synonym 2"),
            "EMAP:0000001",
            "EMAP term",
            "A:0000001",
            "anatomy term",
            List.of("anatomy synonym"),
            "E:0000001",
            "embryo anatomy term",
            List.of("E:0000002"),
            List.of("top level embryo anatomy term"),
            "M:0000001",
            "mouse anatomy term",
            List.of("M:0000002"),
            List.of("top level mouse anatomy term"),
            List.of("started1", "started2"),
            List.of("complete1", "complete2"),
            List.of("status1", "status2")
        );
    }

}
