package org.mousephenotype.impcsolrdocumentation.generator;

import org.mousephenotype.impcsolrdocumentation.model.StatisticalResult;

import java.util.List;

public class StatisticalResultGenerator {


    public static StatisticalResult generateExampleStatisticalResultResponse() {
        return new StatisticalResult(
            "DOC123",
            100L,
            "Gene Expression",
            List.of("AID123", "AID456"),
            List.of("Heart", "Liver"),
            List.of("IAID789", "IAID101"),
            List.of("Ventricle", "Lobe"),
            List.of("TAID112", "TAID113"),
            List.of("Circulatory System", "Digestive System"),
            List.of("MPID123", "MPID456"),
            List.of("Hypertrophy", "Necrosis"),
            "MPID789",
            "Atrophy",
            List.of("TMPID123", "TMPID456"),
            List.of("Muscle Structure", "Cell Death"),
            List.of("IMPID789", "IMPID101"),
            List.of("Muscle Size", "Apoptosis"),
            "MMPID123",
            "Male Hypertrophy",
            List.of("MTMPID123", "MTMPID456"),
            List.of("Male Muscle Structure", "Male Cell Death"),
            List.of("MIMPID789", "MIMPID101"),
            List.of("Male Muscle Size", "Male Apoptosis"),
            "FMPID123",
            "Female Hypertrophy",
            List.of("FTMPID123", "FTMPID456"),
            List.of("Female Muscle Structure", "Female Cell Death"),
            List.of("FIMPID789", "FIMPID101"),
            List.of("Female Muscle Size", "Female Apoptosis"),
            "Resource Name",
            "Full Resource Name",
            200L,
            List.of("Project X", "Project Y"),
            "Center Z",
            "PID123",
            300L,
            "Pipeline Name",
            400L,
            List.of("PRID123", "PRID456"),
            List.of(500L, 600L),
            "Procedure Name",
            700L,
            "PAID123",
            List.of(800L),
            "Parameter Name",
            900L,
            "Colony123",
            "Gene123",
            "M123456",
            "Allele123",
            "Allele Name",
            "A123456",
            "Strain Name",
            "S123456",
            "Male",
            "Homozygote",
            "Random",
            "Weight",
            "Group1",
            "Frame1",
            "C57BL/6N",
            "EMBL-EBI",
            101L,
            102L,
            103L,
            104L,
            105L,
            0.5,
            1.5,
            0.4,
            1.4,
            0.5,
            0.6,
            0.7,
            0.8,
            0.9,
            1.0,
            List.of("Category 1", "Category 2"),
            0.07,
            1.1,
            true,
            false,
            0.08,
            0.09,
            0.10,
            0.11,
            "10%",
            "20%",
            0.12,
            0.13,
            0.14,
            0.15,
            0.16,
            0.17,
            0.20,
            0.21,
            0.22,
            0.23,
            true,
            0.24,
            0.25,
            0.26,
            0.27,
            0.28,
            0.29,
            0.30,
            0.31,
            0.32,
            "Tag1",
            List.of("Male", "Female"),
            "LS:001",
            "Adulthood",
            true,
            "Medium",
            "Gaussian",
            "3",
            "10",
            "50",
            "0.05",
            "5",
            "Doe Note Example",
            List.of("Metadata1", "Metadata2"),
            8.3,
            79,
            7,
            6.3,
            8.5,
            9.2,
            4.1,
            "control",
            4.3,
            "experimental",
            4.3,
            23,
            21,
            9.2,
            9.2,
            0.6,
            "Linear Mixed Model framework, LME, including Weight",
            "Successful"
        );
    }

}
